import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { normalizeSize, parseMm } from '../src/utils/tileCalculation.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const fields = ['id', 'name', 'sizeMm', 'finish', 'surface', 'collection', 'pcsPerBox', 'coverageSqFt', 'confidence']
const sources = [
  ['floorSizeCalculator.json', 'Global Floor', 'Floor'],
  ['wallSizeCalculator.json', 'Global Wall', 'Wall'],
  ['sunfloraSizeCalculator.json', 'Sunflora 2×4', 'Floor & Wall'],
  ['sky12x18SizeCalculator.json', 'Sky 12×18', 'Wall'],
  ['skypeSizeCalculator.json', 'Skype 2×4', 'Floor & Wall'],
]

// Preserve the existing calculation data and order. Image URLs, extraction
// notes, OCR boxes and other offline fields are never downloaded by the UI.
const products = sources.flatMap(([filename, collection, surfaceDefault]) => {
  const seed = JSON.parse(fs.readFileSync(path.join(root, 'src/data', filename), 'utf8'))
  return (seed.products || []).flatMap(product => {
    const sizeMm = normalizeSize(product.sizeMm || product.size || '')
    const confidence = product.confidence || (product.ocrOk === false ? 'placeholder' : 'high')
    if (!sizeMm || confidence === 'non_product') return []
    return [{
      id: product.id,
      name: product.name || product.id,
      sizeMm,
      finish: product.finish || '',
      surface: product.surface || surfaceDefault || 'Floor',
      collection,
      pcsPerBox: product.pcsPerBox != null && product.pcsPerBox !== '' ? Number(product.pcsPerBox) : null,
      coverageSqFt: product.coverageSqFt != null && product.coverageSqFt !== '' ? Number(product.coverageSqFt) : null,
      confidence: ['high', 'medium'].includes(confidence) ? confidence : 'placeholder',
    }]
  })
})

const sizes = new Map()
for (const product of products) {
  const size = sizes.get(product.sizeMm) || { sizeMm: product.sizeMm, count: 0, surfaces: new Set() }
  size.count++
  String(product.surface).split(/[&,/]/).map(value => value.trim()).filter(Boolean).forEach(value => size.surfaces.add(value))
  sizes.set(product.sizeMm, size)
}
const sizeOptions = [...sizes.values()].map(size => ({ ...size, surfaces: [...size.surfaces] })).sort((a, b) => {
  const da = parseMm(a.sizeMm)
  const db = parseMm(b.sizeMm)
  return (da ? da.w * da.h : 0) - (db ? db.w * db.h : 0) || a.sizeMm.localeCompare(b.sizeMm)
})
const index = {
  fields,
  products: products.map(product => fields.map(field => product[field])),
  sizeOptions,
  collections: [{ id: 'all', label: 'All collections' }, ...sources.map(([, collection]) => ({ id: collection, label: collection }))],
}
const output = path.join(root, 'src/data/sizeCalculator.generated.js')
const content = `// Generated by scripts/build_size_calculator.mjs; edit the source seeds instead.\nexport default ${JSON.stringify(index)}\n`
if (process.argv.includes('--check')) {
  if (!fs.existsSync(output) || fs.readFileSync(output, 'utf8') !== content) throw new Error('Calculator index is stale. Run node scripts/build_size_calculator.mjs')
} else fs.writeFileSync(output, content)
console.log(`Calculator index: ${products.length} products, ${(Buffer.byteLength(content) / 1024).toFixed(1)} KiB; no image assets or OCR metadata.`)
