// Run before Vite. Static policy/error pages need no catalogue JavaScript.
// --check verifies generated files without changing them.
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { business } from '../src/data/siteConfig.js'
import { PRODUCTION_ORIGIN, siteSeo } from '../src/data/seo.js'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const check = process.argv.includes('--check')
const escapeHtml = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;')
const absolute = pathname => new URL(pathname, PRODUCTION_ORIGIN).href
const favicon = '<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />\n    <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png" />'

export function metadata({ title, description, pathname = '/', noindex = false }) {
  return `<title>${escapeHtml(title)}</title>
    <meta name="description" content="${escapeHtml(description)}" />
    <meta name="robots" content="${noindex ? 'noindex, follow' : 'index, follow, max-image-preview:large'}" />
    ${noindex ? '' : `<link rel="canonical" href="${absolute(pathname)}" />`}
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="${escapeHtml(business.name)}" />
    <meta property="og:locale" content="en_IN" />
    <meta property="og:title" content="${escapeHtml(title)}" />
    <meta property="og:description" content="${escapeHtml(description)}" />
    ${noindex ? '' : `<meta property="og:url" content="${absolute(pathname)}" />`}
    <meta property="og:image" content="${absolute(siteSeo.socialImage)}" />
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
    <meta property="og:image:type" content="image/jpeg" />
    <meta property="og:image:alt" content="${escapeHtml(siteSeo.socialImageAlt)}" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="${escapeHtml(title)}" />
    <meta name="twitter:description" content="${escapeHtml(description)}" />
    <meta name="twitter:image" content="${absolute(siteSeo.socialImage)}" />
    <meta name="twitter:image:alt" content="${escapeHtml(siteSeo.socialImageAlt)}" />`
}

const schema = {
  '@context': 'https://schema.org',
  '@graph': [
    {
      '@type': 'HomeGoodsStore', '@id': absolute('/#showroom'),
      name: business.name, url: absolute('/'), description: business.intro,
      telephone: business.phoneTel, image: absolute(siteSeo.socialImage), logo: absolute('/favicon-192.png'),
      address: {
        '@type': 'PostalAddress', streetAddress: `${business.address.line1}, ${business.address.line2}`,
        addressLocality: business.address.city, addressRegion: business.address.state,
        postalCode: business.address.pin, addressCountry: 'IN',
      },
      // The daily hours printed on the site; no inferred coordinates, stock,
      // prices, social profiles or placeholder customer ratings.
      openingHours: 'Mo-Su 09:00-20:00',
    },
    {
      '@type': 'WebSite', '@id': absolute('/#website'), url: absolute('/'),
      name: business.name, inLanguage: 'en-IN', publisher: { '@id': absolute('/#showroom') },
    },
  ],
}
const headBlock = `<!-- site-metadata:start (generated by scripts/build_site_pages.mjs) -->
    ${metadata(siteSeo)}
    <script type="application/ld+json">${JSON.stringify(schema).replaceAll('<', '\\u003c')}</script>
    <!-- site-metadata:end -->`

function shell({ title, description, pathname, noindex, body }) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#2C1A0E" />
    ${favicon}
    ${metadata({ title, description, pathname, noindex })}
    <link rel="stylesheet" href="/site-pages.css" />
  </head>
  <body>
    <a class="skip-link" href="#content">Skip to content</a>
    <header class="site-header">
      <a class="brand" href="/#home"><img src="/favicon-192.png" width="42" height="42" alt="" /><span>${escapeHtml(business.shortName)}<small>Tiles &amp; Stone</small></span></a>
      <nav aria-label="Main"><a href="/#visualizer">Catalogues</a><a class="desktop-link" href="/#contact">Visit us</a></nav>
    </header>
    ${body}
    <footer class="site-footer"><p>${escapeHtml(business.name)} · ${escapeHtml(business.address.city)}, ${escapeHtml(business.address.state)}</p><a href="/#privacy-settings">Cookie preferences</a></footer>
  </body>
</html>
`
}

const privacy = shell({
  title: siteSeo.privacyTitle, description: siteSeo.privacyDescription, pathname: '/privacy-policy',
  body: `<main id="content">
      <p class="eyebrow">Your visit, your choice</p>
      <h1>Privacy &amp; cookies</h1>
      <p class="lede">You can explore our catalogues without creating an account. Here is how this website handles your information and optional services.</p>
      <p class="updated">Updated 19 September 2026</p>
      <div class="document">
        <section aria-labelledby="enquiries"><h2 id="enquiries">Enquiries you choose to share</h2>
          <p>The enquiry form prepares a WhatsApp message in your browser. Your name, phone number and project details stay in the page’s memory until you choose <strong>Review in WhatsApp</strong>. Opening that link passes the draft to WhatsApp; you decide whether to send it there.</p>
          <p>The website has no form submission server and does not save your form fields in browser storage. Reloading or closing the page clears the draft. Once you contact the showroom through WhatsApp or by phone, your conversation is handled through that service and by the showroom to respond to your enquiry.</p>
          <p>A shared catalogue link includes the selected collection, page and design. It does not include your contact form details.</p>
        </section>
        <section aria-labelledby="storage"><h2 id="storage">Cookies &amp; browser storage</h2>
          <p>This website does not use advertising or analytics cookies. It uses small browser storage entries for the following purposes:</p>
          <ul>
            <li><strong>Your cookie choice:</strong> <code>sidhhi-cookie-preferences</code> in local storage remembers whether you allow the optional Google Maps embed. The preference expires after 180 days, when we ask again. It contains your choice and its date, not your form details.</li>
            <li><strong>Repeated enquiry protection:</strong> <code>sidhhi-enquiry-cooldown</code> in session storage holds a preparation time to limit repeated drafts within 30 seconds. It contains no enquiry text and is cleared when the browser tab’s session ends.</li>
          </ul>
          <p>You can change your choice through <a href="/#privacy-settings">Cookie preferences</a>, or remove these entries using your browser’s site-data controls. If preference storage is unavailable, the embedded map stays off.</p>
        </section>
        <section aria-labelledby="maps"><h2 id="maps">Optional Google Maps</h2>
          <p>We load the embedded map only after you allow it. Loading it connects your browser to Google, which may receive your IP address and device information and may use cookies under <a href="https://policies.google.com/privacy" rel="noopener noreferrer">Google’s privacy policy</a>.</p>
          <p>You can withdraw permission in Cookie preferences. This removes the embed and stops further embedded-map requests; it cannot delete information already received by Google or its existing cookies. The separate directions link opens Google Maps only when you choose to visit it.</p>
        </section>
        <section aria-labelledby="hosting"><h2 id="hosting">Hosting &amp; external services</h2>
          <p>Vercel hosts this website. Requests for pages and catalogue images include technical information such as your IP address, browser information and requested URL. The hosting provider may process this information to deliver and protect the service. See <a href="https://vercel.com/legal/privacy-notice" rel="noopener noreferrer">Vercel’s privacy notice</a>.</p>
          <p>Fonts and catalogue artwork are served with this website. Links to WhatsApp, Google Maps and other external websites are governed by those services’ own policies once you open them.</p>
        </section>
        <section aria-labelledby="contact"><h2 id="contact">Contact the showroom</h2>
          <p>For questions about this notice or information you have shared with us, call <a href="tel:${business.phoneTel}">${escapeHtml(business.phoneDisplay)}</a> or visit ${escapeHtml(business.address.full)}.</p>
          <p>We will update this page if the website’s information-handling features change.</p>
        </section>
      </div>
      <div class="actions"><a class="action action-primary" href="/#privacy-settings">Cookie preferences</a><a class="action" href="/#visualizer">Explore catalogues</a></div>
    </main>`,
})

const notFound = shell({
  title: 'Page Not Found | Sidhhi Binayak Tiles', description: 'This page could not be found. Return to the showroom website or explore the tile and sanitaryware catalogues.', noindex: true,
  body: `<main id="content" class="not-found">
      <div class="glass-note"><p class="eyebrow">404 · Page not found</p>
        <h1>A different path to your perfect finish.</h1>
        <p class="lede">This link may have moved, or the address may be incomplete. Our collections are still here to explore.</p>
        <div class="actions"><a class="action action-primary" href="/#visualizer">Explore catalogues</a><a class="action" href="/#home">Back to home</a></div>
      </div>
    </main>`,
})

// Copy only canonical root tokens, avoiding a second hand-maintained palette.
const sourceStyles = await Promise.all(['src/index.css', 'src/styles/site-glass.css'].map(name => readFile(path.join(root, name), 'utf8')))
const declarations = new Map()
for (const css of sourceStyles) {
  const block = css.match(/:root\s*\{([\s\S]*?)\}/)?.[1] || ''
  for (const [, name, value] of block.matchAll(/(--[\w-]+)\s*:\s*([^;]+);/g)) declarations.set(name, value.trim())
}
const tokens = `:root {\n${[...declarations].map(([name, value]) => `  ${name}: ${value};`).join('\n')}\n}\n`
const fonts = await readFile(path.join(root, 'src/styles/fonts.css'), 'utf8').catch(() => '')
const css = `/* Generated by scripts/build_site_pages.mjs; edit its sources. */\n${fonts}\n${tokens}\n${await readFile(path.join(root, 'scripts/site-pages.css'), 'utf8')}`
const indexSource = await readFile(path.join(root, 'index.html'), 'utf8')
if (!indexSource.includes('<!-- site-metadata:start')) throw new Error('index.html is missing the managed metadata marker')
const index = indexSource.replace(/<!-- site-metadata:start[\s\S]*?<!-- site-metadata:end -->/, headBlock)
const outputs = new Map([
  ['index.html', index],
  ['public/privacy-policy/index.html', privacy],
  ['public/404.html', notFound],
  ['public/site-pages.css', css],
  ['public/robots.txt', `User-agent: *\nAllow: /\n\nSitemap: ${absolute('/sitemap.xml')}\n`],
  ['public/sitemap.xml', `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n  <url><loc>${absolute('/')}</loc></url>\n  <url><loc>${absolute('/privacy-policy')}</loc></url>\n</urlset>\n`],
])
for (const [name, content] of outputs) {
  const target = path.join(root, name)
  if (check) {
    if (await readFile(target, 'utf8').catch(() => '') !== content) throw new Error(`${name} is stale. Run node scripts/build_site_pages.mjs --prepare`)
  } else {
    await mkdir(path.dirname(target), { recursive: true })
    await writeFile(target, content)
  }
}
console.log(`${check ? 'Verified' : 'Prepared'} home metadata, privacy policy, custom 404, sitemap and robots.txt.`)
