import { createHash } from 'node:crypto'
import { readFile, writeFile, mkdir, stat } from 'node:fs/promises'
import { basename, join } from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import sharp from 'sharp'
import { products } from '../src/data/catalogue.js'

const root = fileURLToPath(new URL('../', import.meta.url))
const outputDirectory = join(root, 'public/assets/catalogue/responsive')
const manifestFile = join(root, 'src/data/responsiveImageManifest.js')
const widths = [320, 640, 960]
const quality = 80
const pipeline = `webp-v1-quality${quality}-widths${widths.join('-')}`
const checkOnly = process.argv.includes('--check')
const sources = [...new Set(products.map(product => product.imageUrl).filter(Boolean))].sort()
let previous = { default: {}, sourceHashes: {}, imagePipeline: null }
try { previous = await import(pathToFileURL(manifestFile).href) } catch (error) {
  if (error.code !== 'ERR_MODULE_NOT_FOUND') throw error
}
if (!checkOnly) await mkdir(outputDirectory, { recursive: true })
sharp.concurrency(2)

const records = new Map()
const sourceHashes = {}
const byteCounts = new Map()
let written = 0
let cached = 0
let cursor = 0

async function processSource(url) {
  if (!/^\/assets\/catalogue\/[^?#]+\.(?:webp|png|jpe?g)$/i.test(url) || url.includes('..') || url.includes('\\')) {
    throw new Error(`Unexpected catalogue image source: ${url}`)
  }
  const source = await readFile(join(root, 'public', url.slice(1)))
  const hash = createHash('sha256').update(pipeline).update(url).update(source).digest('hex').slice(0, 12)
  sourceHashes[url] = hash
  const prior = previous.default[url]
  if (previous.imagePipeline === pipeline && previous.sourceHashes[url] === hash && prior) {
    const available = await Promise.all(prior.variants.map(async variant => {
      try {
        const file = await stat(join(root, 'public', variant.src.slice(1)))
        return file.size > 0 ? file.size : 0
      } catch { return 0 }
    }))
    if (available.every(Boolean)) {
      records.set(url, prior)
      byteCounts.set(url, { original: source.length, variants: available })
      cached += prior.variants.length
      return
    }
  }
  if (checkOnly) throw new Error(`Responsive images need regeneration for ${url}; run npm run build:images`)

  const metadata = await sharp(source).metadata()
  const rotated = metadata.orientation >= 5 && metadata.orientation <= 8
  const width = rotated ? metadata.height : metadata.width
  const height = rotated ? metadata.width : metadata.height
  if (!width || !height) throw new Error(`Image has no usable dimensions: ${url}`)
  const variants = []
  const variantBytes = []
  for (const targetWidth of widths.filter(value => value < width)) {
    // Only catalogue photographs enter this pipeline. No crop, saturation,
    // sharpening, compositing or changes to the original 3D textures.
    const { data, info } = await sharp(source).rotate()
      .resize({ width: targetWidth, withoutEnlargement: true })
      .toColourspace('srgb').webp({ quality, effort: 5 })
      .toBuffer({ resolveWithObject: true })
    // A larger download is never a useful responsive candidate.
    if (data.length >= source.length) continue
    const filename = `${basename(url).replace(/\.[^.]+$/, '')}-${hash}-${info.width}.webp`
    await writeFile(join(outputDirectory, filename), data)
    variants.push({ src: `/assets/catalogue/responsive/${filename}`, width: info.width })
    variantBytes.push(data.length)
    written += 1
  }
  records.set(url, { width, height, variants })
  byteCounts.set(url, { original: source.length, variants: variantBytes })
}

await Promise.all(Array.from({ length: 4 }, async () => {
  while (cursor < sources.length) {
    const index = cursor++
    await processSource(sources[index])
  }
}))

const manifest = Object.fromEntries(sources.map(url => [url, records.get(url)]))
const hashes = Object.fromEntries(sources.map(url => [url, sourceHashes[url]]))
if (!checkOnly) {
  const generated = `// Generated by scripts/build_responsive_images.mjs. Do not edit by hand.\n`
    + `// Original catalogue photos and visualizer textures are preserved.\n`
    + `export const imagePipeline = ${JSON.stringify(pipeline)}\n`
    + `export const sourceHashes = ${JSON.stringify(hashes, null, 2)}\n`
    + `export default ${JSON.stringify(manifest, null, 2)}\n`
  const existing = await readFile(manifestFile, 'utf8').catch(() => null)
  if (existing !== generated) await writeFile(manifestFile, generated)
}

function pageBytes(count, targetWidth) {
  let original = 0
  let responsive = 0
  for (const product of products.slice(0, count)) {
    if (!product.imageUrl) continue
    const entry = manifest[product.imageUrl]
    const bytes = byteCounts.get(product.imageUrl)
    const index = entry.variants.findIndex(variant => variant.width >= targetWidth)
    original += bytes.original
    responsive += index >= 0 ? bytes.variants[index] : bytes.original
  }
  return { original, responsive, savingPercent: Math.round((1 - responsive / original) * 100) }
}
const report = {
  sources: sources.length, written, cached,
  derivativeFiles: [...records.values()].reduce((total, entry) => total + entry.variants.length, 0),
  derivativeBytes: [...byteCounts.values()].reduce((total, entry) => total + entry.variants.reduce((sum, bytes) => sum + bytes, 0), 0),
  // 390px phone: ~169px CSS image at DPR2 -> a640px candidate.
  phone390Dpr2: pageBytes(6, 338),
  // 1440px desktop: ~403px CSS image at DPR1/DPR2.
  desktop1440Dpr1: pageBytes(24, 403),
  desktop1440Dpr2: pageBytes(24, 806),
}
console.log(JSON.stringify(report, null, 2))
if (!checkOnly) {
  await mkdir(join(root, 'build-artifacts'), { recursive: true })
  await writeFile(join(root, 'build-artifacts/responsive-images-report.json'), JSON.stringify(report, null, 2))
}
